### ISSUE TITLE
Tarea para casa

### ISSUE THREAD

**Issue by Emanueldamianpaz** [mariaclarasegura/maven-example#1]
Cosas a hacer

- [x] Cambiar todo a inglés
- [x] Modificar el json de respuesta para que sea `SNAKE_CASE`
- [x] El json debe incluir el tipo de consumible que es (actualmente no se especifica si es hamburguesa, u otra cosa)
- [x] Pensar un nombre para el "emprendimiento"
- [ ] Que los endpoints arranquen con ese nombre. 
Ejemplo:
   - `/<emprendimiento>/listado` 
   - `/<emprendimiento>/listado/<consumible>`

**Comment by mariaclarasegura** [comment]
Resuelto
